baseURL = "https://f33ot1.github.io/"
languageCode = "en-us"
title = "malicious unicorn"
theme = "PaperMod"
publishDir = "./docs"
        
[params]
  defaultTheme = "dark"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "learning"
    name = "Learning"
    url = "/learning/"
    weight = 4

