baseURL = "https://f33ot1.github.io/"
languageCode = "en-us"
title = "cabin C086"
theme = "PaperMod"
publishDir = "./docs"
        
[params]
  defaultTheme = "dark"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "https://f33ot1.github.io/about/"
    weight = 1

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "https://f33ot1.github.io/contact/"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "https://f33ot1.github.io/projects/"
    weight = 3

  [[menu.main]]
    identifier = "learning"
    name = "learning"
    url = "https://f33ot1.github.io/learning/"
    weight = 4

